version: 1.0.{build}
build:
  project: YellowDrawer.Storage.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
  
after_build:
- nuget pack YellowDrawer.Storage.Azure\YellowDrawer.Storage.Azure.nuspec  -Version "%APPVEYOR_BUILD_VERSION%" -OutputDirectory YellowDrawer.Storage.Azure
- nuget pack YellowDrawer.Storage.Amazon\YellowDrawer.Storage.Amazon.nuspec  -Version "%APPVEYOR_BUILD_VERSION%" -OutputDirectory YellowDrawer.Storage.Amazon
- nuget pack YellowDrawer.Storage.GridFS\YellowDrawer.Storage.GridFS.nuspec  -Version "%APPVEYOR_BUILD_VERSION%" -OutputDirectory YellowDrawer.Storage.GridFS
- nuget pack YellowDrawer.Storage.Common\YellowDrawer.Storage.Common.nuspec  -Version "%APPVEYOR_BUILD_VERSION%" -OutputDirectory YellowDrawer.Storage.Common

test:
  categories:
    except:
      - Unit

artifacts:
- path: 'YellowDrawer.Storage.Azure\*.nupkg'
  name: YellowDrawer.Storage.Azure
- path: 'YellowDrawer.Storage.Amazon\*.nupkg'
  name: YellowDrawer.Storage.Amazon
- path: 'YellowDrawer.Storage.GridFS\*.nupkg'
  name: YellowDrawer.Storage.GridFS
- path: 'YellowDrawer.Storage.Common\*.nupkg'
  name: YellowDrawer.Storage.Common
  
install:
  - nuget restore YellowDrawer.Storage.sln

deploy:
- provider: NuGet
  api_key: fa0bd176-3bdd-49d9-afd1-635b1965fa13
  artifact: YellowDrawer.Storage.Azure  
- provider: NuGet
  api_key: fa0bd176-3bdd-49d9-afd1-635b1965fa13
  artifact: YellowDrawer.Storage.Amazon
- provider: NuGet
  api_key: fa0bd176-3bdd-49d9-afd1-635b1965fa13
  artifact: YellowDrawer.Storage.GridFS  
- provider: NuGet
  api_key: fa0bd176-3bdd-49d9-afd1-635b1965fa13
  artifact: YellowDrawer.Storage.Common
  
